- .circleci/config.yml
The existing config file erroneously requests an image with SDK 25 instead. Perhaps this will fix the failures we've been seeing?
> [CI] - ensure SDK 27 is installed for CircleCI

- db/src/main/kotlin/edu/artic/db/daos/ArticObjectDao.kt
- db/src/main/kotlin/edu/artic/db/models/ArticGallery.kt
- map/src/main/kotlin/edu/artic/map/MapFragment.kt
- map/src/main/kotlin/edu/artic/map/MapViewModel.kt
This includes some much-wanted documentation of the `MapViewModel` class, as well as a fix for the inconsistent loading issue. As a bonus, we can now use the usual channels to tell the fragment that our map needs to be cleared of all markers.
> Map department pins are transient (AIC-251)

- base/src/main/java/edu/artic/base/utils/GlideRequestBuilderExtensions.kt
- map/src/main/kotlin/edu/artic/map/MapFragment.kt
- map/src/main/kotlin/edu/artic/map/util/ArticObjectMarkerGenerator.kt
- map/src/main/res/layout/marker_gallery_number.xml
- welcome/src/main/kotlin/edu/artic/welcome/GlideModule.kt
In release builds, glide will no longer print lots of stacktraces to logcat. Also:
* reduced memory usage when rendering a non-square image
* progressive loading of thumbnail then full image
> [Glide] reduce error verbosity

- adapter/src/main/java/edu/artic/adapter/BaseAdapterBinder.kt
- adapter/src/main/res/values/ids.xml
- audio/build.gradle
- audio/src/main/java/edu/artic/audio/AudioDetailsFragment.kt
- audio/src/main/java/edu/artic/audio/LanguageAdapter.kt
- audio/src/main/res/layout/view_language_box.xml
1. Add conversion methods for turning `BaseRecyclerViewAdapter` into a `BaseAdapter` via `BaseAdapterBinder`.
2. Provide `DropDownAdapter` interface mixin which gives the adapter ability to render different dropdown view than regular view.
3. Remove need for `audioIntent` from `AudioDetailsFragment`.
> Convert LanguageAdapter implementation into RecyclerViewAdapter converter

- audio/src/main/res/drawable/ic_audio_large.xml
- audio/src/main/res/layout/fragment_audio_lookup.xml
Nothing much here, the new asset has hollow circles instead of filled-in circles. It's also slightly larger (24dp -> 48dp a side).
> Switch to approved audio lookup icon (AIC-326)

- adapter/src/main/java/edu/artic/adapter/AutoHolderRecyclerViewAdapter.kt
- adapter/src/main/java/edu/artic/adapter/BaseRecyclerViewAdapter.kt
- adapter/src/main/java/edu/artic/adapter/RXExtensions.kt
- audio/src/main/java/edu/artic/audio/AudioLookupFragment.kt
- events/src/main/kotlin/edu/artic/events/AllEventsFragment.kt
- exhibitions/src/main/kotlin/edu/artic/exhibitions/AllExhibitionsFragment.kt
- tours/src/main/kotlin/edu/artic/tours/AllToursFragment.kt
- welcome/src/main/kotlin/edu/artic/welcome/WelcomeFragment.kt
There were some omissions in the description of these classes. Note that `BaseRecyclerViewAdapter` was added during the 'Tours Summary' PR, #4 . We'll need to update the licenses on these files as well to reflect their provenance - that shall be a separate PR, some time next week.
> Update documentation around custom adapters

- base/src/main/java/edu/artic/base/utils/ActivityExtensions.kt
- media_ui/src/main/java/edu/artic/media/ui/NarrowAudioPlayerFragment.kt
- ui/src/main/kotlin/edu/artic/ui/BaseFragment.kt
Updates
* Instead of getting the specific color we pull the color by attribute defined in active theme so that it is dynamic and applies correct color.
* Marks the fragments `AloofFragment` if they are not suppose to modify parent activity's theme
> Statusbar color issue fix 

- audio/src/main/res/color/number_pad_white_tangible.xml
- audio/src/main/res/color/number_pad_white_translucent.xml
- audio/src/main/res/drawable/number_pad_circle.xml
- audio/src/main/res/drawable/number_pad_delete.xml
This uses a 50% transparency overlay for the 'numeric' and 'go' buttons.
A special dispensation is made for the 'delete back' button, which does not use an overlay. Instead, its outline brightens to a solid white when pressed.
> Add press-states to the number pad buttons (AIC-330)

- search/src/main/java/artic/edu/search/RetrofitSearchServiceProvider.kt
- search/src/main/java/artic/edu/search/SearchApi.kt
- search/src/main/java/artic/edu/search/SearchFragment.kt
- search/src/main/java/artic/edu/search/SearchModule.kt
- search/src/main/java/artic/edu/search/SearchServiceProvider.kt
- search/src/main/java/artic/edu/search/SearchViewModel.kt
- search/src/main/res/layout/activity_search.xml
- search/src/main/res/layout/fragment_search.xml
- search/src/main/res/layout/search_app_bar_layout.xml
This adds a new `SearchApi` class, along with a `SearchServiceProvider` abstracting that away from the ViewModel.
I've left off the actual execution of the api calls and the binding of search results for now; I expect those'll need more attention so I excluded them from this PR.
> Basic Search backend (AIC-342)

- audio/src/main/AndroidManifest.xml
- audio/src/main/java/edu/artic/audio/AudioActivity.kt
- audio/src/main/java/edu/artic/audio/AudioLookupFragment.kt
- ui/src/main/kotlin/edu/artic/ui/BaseFragment.kt
- viewmodel/src/main/kotlin/edu/artic/viewmodel/BaseViewModelFragment.kt
- viewmodel/src/main/kotlin/edu/artic/viewmodel/NavViewViewModel.kt
This is intended to resolve some visual problems and some (at first glance inconsistent) behavior.
Sample issue: navigate in the following pattern:
1. Hit 'audio'
2. Hit 'home' (do NOT use the back button)
3. Hit 'audio'
3a. Each button press on the number pad will be registered twice.
3b. This includes the 'Go' button - we can go only once, and the second invocation triggers a crash
Each subsequent load of the 'audio' screen in the same manner as steps 1. and 2. will register an extra subscription and cause more trouble. The number of duplicate button presses is capped at 5 but the subscription count is unlimited.
Work done in this branch:
*    Document navigationDisposeBag in the code itself
*    Restrict standard binding to one resume per create-destroy lifecycle
*    Run …
> Reduce duplicate RX subscriptions (AIC-349)

- audio/src/main/java/edu/artic/audio/AudioActivity.kt
- base/src/main/java/edu/artic/base/utils/ViewExtensions.kt
- info/src/main/java/edu/artic/info/InfoActivity.kt
- map/src/main/kotlin/edu/artic/map/MapActivity.kt
- navigation/src/main/java/edu/artic/navigation/NavigationSelectListener.kt
- welcome/src/main/kotlin/edu/artic/welcome/WelcomeActivity.kt
This is a followup to #100. I noticed that we go through a wasteful `pause`-`resume` cycle whenever the icon for the current section of the app is tapped.
In addition, such intents overwrite the original launch intent and unnecessarily encumber diagnosis of navigation graph issues. This PR includes the logic needed to `preventReselection()` - see inline documentation for more details.
> Ignore duplicate clicks on bottom nav (AIC-363)

- audio/src/main/java/edu/artic/audio/AudioDetailsFragment.kt
- audio/src/main/java/edu/artic/audio/AudioDetailsViewModel.kt
- localization/src/main/kotlin/edu/artic/localization/LocalizationPreferences.kt
- media/src/main/java/edu/artic/media/audio/AudioPlayerService.kt
When you visit the audio details page after starting a tour in a different language, the audio file will switch back to the app language. This is a problem.
> Tour language must persist (AIC-355)

- base/src/main/res/values/strings.xml
- map/src/main/kotlin/edu/artic/map/MapFragment.kt
- map/src/main/kotlin/edu/artic/map/MapModule.kt
- map/src/main/kotlin/edu/artic/map/MapViewModel.kt
- map/src/main/kotlin/edu/artic/map/carousel/LeaveCurrentTourDialogFragment.kt
- map/src/main/kotlin/edu/artic/map/carousel/TourProgressManager.kt
- map/src/main/res/layout/fragment_leave_tour_dialog.xml
- map/src/main/res/values/dimens.xml
- map/src/main/res/values/styles.xml
- ui/src/main/kotlin/edu/artic/ui/BaseFragment.kt
Changes:
* Updates leave tour dialog design
* Refactors leave tour dialog to use DialogFragment instead of AlertDialog 
* Adds `next tour` in tour progress manager for queuing the requested tour (it will be displayed if the user leaves active tour)
> Refactor and leave tour dialog design update

- db/src/main/kotlin/edu/artic/db/AppDataManager.kt
- db/src/main/kotlin/edu/artic/db/AppDataState.kt
- db/src/main/kotlin/edu/artic/db/RetrofitAppDataServiceProvider.kt
- splash/src/main/kotlin/edu/artic/splash/SplashActivity.kt
- splash/src/main/kotlin/edu/artic/splash/SplashViewModel.kt
- splash/src/main/res/layout/activity_splash.xml
I know that we've got a much nicer splash screen planned out. Nevertheless, I felt there were some minor improvements we could make now without significant churn. Additionally, we will need the load-level error handling logic no matter what kind of splash screen we end up displaying.
* Progress percentage is fixed-width
* Errors thrown during load are shown in place of progress text and do not crash app
* Progress text is larger font size and black instead of grey for heightened contrast
NB: only the first error will appear on screen. I feel this is acceptable for now.
> Minor splash improvements (AIC-380)

- db/src/main/kotlin/edu/artic/db/AppDataManager.kt
- db/src/main/kotlin/edu/artic/db/daos/ArticDataObjectDao.kt
- db/src/main/kotlin/edu/artic/db/daos/GeneralInfoDao.kt
This covers some work found during stress-testing of #111, after it had been merged in. Essentially, the code as written checked whether the `appData-v2.json` headers have the same timestamp as the one we keep on record in `SharedPreferences`. If they matched, we assumed:
1. the database is not empty
and
2. the database contains all of the content necessary to run the app
These assumptions cause some trouble when switching devices or reinstalling the app (as happens regularly during QA stress-testing). To mitigate them, the attached changes will discard our recorded timestamp if
* the database is empty or
* the database is missing the crucial `GeneralInfo` data or
* the database is missing the crucial `DataObject` data.
It also delays the actual recording of that timestamp until we have …
> App Data Verification (AIC-380)

- db/src/main/kotlin/edu/artic/db/daos/ArticMapAnnotationDao.kt
- db/src/main/kotlin/edu/artic/db/models/ArticMapAnnotation.kt
- details/src/main/kotlin/edu/artic/tours/TourDetailsViewModel.kt
- map/src/main/kotlin/edu/artic/map/MapConstructs.kt
- map/src/main/kotlin/edu/artic/map/MapFragment.kt
- map/src/main/kotlin/edu/artic/map/MapMarkerConstructor.kt
- map/src/main/kotlin/edu/artic/map/MapViewModel.kt
- map/src/main/kotlin/edu/artic/map/SearchManager.kt
- map/src/main/kotlin/edu/artic/map/SearchObjectDetailsFragment.kt
- map/src/main/kotlin/edu/artic/map/SearchObjectDetailsViewModel.kt
- map/src/main/kotlin/edu/artic/map/SearchedObjectsAdapter.kt
- map/src/main/kotlin/edu/artic/map/carousel/TourCarouselViewModel.kt
- map/src/main/kotlin/edu/artic/map/rendering/MapItemRenderers.kt
- map/src/main/kotlin/edu/artic/map/rendering/ObjectsMapItemRenderer.kt
- map/src/main/res/layout/fragment_search_object_details.xml
- map/src/main/res/layout/layout_amenity_search_cell.xml
- map/src/main/res/layout/layout_artwork_search_cell.xml
- navigation/src/main/java/edu/artic/navigation/NavigationConstants.kt
- search/src/main/java/artic/edu/search/DefaultSearchSuggestionsFragment.kt
- search/src/main/java/artic/edu/search/DefaultSearchSuggestionsViewModel.kt
- search/src/main/java/artic/edu/search/SearchAudioDetailFragment.kt
- search/src/main/java/artic/edu/search/SearchAudioDetailViewModel.kt
- search/src/main/java/artic/edu/search/SearchBaseFragment.kt
- search/src/main/java/artic/edu/search/SearchBaseViewModel.kt
- search/src/main/java/artic/edu/search/SearchResultCellViewModels.kt
- search/src/main/java/artic/edu/search/SearchSuggestedViewModel.kt
- search/src/main/java/artic/edu/search/SuggestedMapAmenity.kt
Updates
* refactors the search object details screen to dispaly different UI depending to search type
- for artwork search, search object details displays artwork details
- for amenity search, it displays amenities of searched type  in map
- for dining amenity search, it displays carousel with dining hours info
* makes searched object pin translucent if it's not in the active floor
> Display search items in map

- db/src/main/kotlin/edu/artic/db/AppDataManager.kt
- db/src/main/kotlin/edu/artic/db/AppDatabase.kt
- db/src/main/kotlin/edu/artic/db/daos/ArticGalleryDao.kt
- db/src/main/kotlin/edu/artic/db/models/ArticExhibition.kt
- db/src/main/kotlin/edu/artic/db/models/ArticGallery.kt
- details/src/main/kotlin/edu/artic/exhibitions/ExhibitionDetailFragment.kt
- details/src/main/kotlin/edu/artic/exhibitions/ExhibitionDetailViewModel.kt
- details/src/main/res/layout/fragment_exhibition_details.xml
This adds a new pair of 'latitude' and 'longitude' properties to the `ArticExhibition` model. They are derived from an associated `ArticGallery` (via the `ArticExhibition.gallery_id` field) at parse time.
Note that these values are optional because
1. the exhibition may not be assigned a `gallery id` at retrieval time
2. there may not be a gallery in the museum with that `gallery id`
3. the matching gallery may not have usable location data
If no value is found for the location data, `ExhibitionDetailsFragment` will hide its `showOnMap` view - this can be used for quick visual smoke testing of the property load logic in a live build.
> Track exhibition location in AppData (AIC-381)

- search/src/main/java/artic/edu/search/SearchResultCellViewModels.kt
- search/src/main/java/artic/edu/search/SearchResultsAdapter.kt
This covers the application of *bold* text to the search query, in the first position found for it to exist. Previously if the same search result stuck around while you typed the *bold* span wouldn't change.
> Search highlight corrections

- map/src/main/kotlin/edu/artic/map/MapConstructs.kt
- map/src/main/kotlin/edu/artic/map/MapFragment.kt
- map/src/main/kotlin/edu/artic/map/MapViewModel.kt
- map/src/main/kotlin/edu/artic/map/SearchManager.kt
- map/src/main/kotlin/edu/artic/map/SearchObjectDetailsFragment.kt
- map/src/main/kotlin/edu/artic/map/SearchObjectDetailsViewModel.kt
- map/src/main/kotlin/edu/artic/map/SearchedObjectsAdapter.kt
- map/src/main/kotlin/edu/artic/map/rendering/ObjectsMapItemRenderer.kt
- search/src/main/java/edu/artic/search/SearchAudioDetailFragment.kt
- search/src/main/java/edu/artic/search/SearchBaseFragment.kt
- search/src/main/java/edu/artic/search/SearchBaseViewModel.kt
Updates:
* Refactors the way objects are sent to the map. `SearchObjectDetailsFragment` now only accepts the proxy object `ArticSearchArtworkObject`. 
* Hides the playback control from search details if no audio translation is available
> Refactors search to map flow (AIC-163)

- db/src/main/kotlin/edu/artic/db/models/ArticObject.kt
- db/src/main/kotlin/edu/artic/db/models/ArticSearchArtworkObject.kt
- map/src/main/kotlin/edu/artic/map/MapFragment.kt
- map/src/main/kotlin/edu/artic/map/MapViewModel.kt
- map/src/main/kotlin/edu/artic/map/SearchObjectDetailsViewModel.kt
- map/src/main/kotlin/edu/artic/map/helpers/ArticObjectExtension.kt
- map/src/main/kotlin/edu/artic/map/helpers/LatLngExtensions.kt
- map/src/main/kotlin/edu/artic/map/rendering/ObjectsMapItemRenderer.kt
- search/src/main/java/edu/artic/search/SearchAudioDetailViewModel.kt
- search/src/main/java/edu/artic/search/SearchBaseFragment.kt
- search/src/main/java/edu/artic/search/SearchBaseViewModel.kt
- search/src/main/java/edu/artic/search/SearchResultCellViewModels.kt
This adds a bunch of map-related documentation and makes sure we only zoom out if a new search object is asked for.
> Fixed on-map pins appear at the wrong zoom (AIC-433)

- search/src/main/res/layout/fragment_search_audio_detail.xml
> Use 'play' icon for `Play Audio` button (AIC-439)

- base/src/main/java/edu/artic/base/utils/IntentExtensions.kt
- map/src/main/kotlin/edu/artic/map/MapActivity.kt
- map/src/main/kotlin/edu/artic/map/MapFragment.kt
Changes :
* Clears the tour object from the bundle.
Since tour object was not removed, the map was presented in tour mode every time the user returned to map (it occurred only when `MapFragment` was resumed).
> Removes tour object from bundle once used (AIC-452)

- audio/src/main/java/edu/artic/audio/AudioDetailsFragment.kt
- audio/src/main/java/edu/artic/audio/AudioDetailsViewModel.kt
- media/src/main/java/edu/artic/media/audio/AudioPlayerService.kt
This ensures that the current audio track is not changed simply because we've navigated to the audio details screen.
To assist in this, it moves most `AudioPlayerService` property detection (i.e. is something playing, what is playing, what language it is playing in, etc.) to the `AudioDetailsViewModel`.
> Select audio track from service (AIC-456)

- map/src/main/kotlin/edu/artic/map/GoogleMapUtil.kt
- map/src/main/kotlin/edu/artic/map/MapFragment.kt
- map/src/main/kotlin/edu/artic/map/MapViewModel.kt
- map/src/main/kotlin/edu/artic/map/helpers/ArticObjectExtension.kt
- map/src/main/kotlin/edu/artic/map/rendering/MapItemRenderer.kt
- map/src/main/kotlin/edu/artic/map/rendering/MapItemRenderers.kt
- map/src/main/kotlin/edu/artic/map/rendering/ObjectsMapItemRenderer.kt
I think the timing of the animations may need a little work. For now, I've set a duration of 500 milliseconds even though the Swift code (in [MapView.swift](https://github.com/art-institute-of-chicago/aic-mobile-ios/blob/0b08e746ca92e/aic/aic/ViewControllers%2BViews/Sections/Map/MapView.swift)) uses 250 milliseconds. More critical though is the actual code changes:
1. Create and use a new `Marker::fadeIn` function
2. Deduplication of visible region changes (prevents stale region info from sticking around)
3. Properly adjust item coords before checking if they're on-screen
4. Small yet handy updates to documentation
Item 3. gave me the most grief - it's the code change in `ObjectsMapItemRenderer.kt` line 108. This logic is irrelevant when there's a constant stream of updates, like when the …
> Fade in markers on floor change (AIC-288)

- map/src/main/kotlin/edu/artic/map/GoogleMapUtil.kt
- map/src/main/kotlin/edu/artic/map/MapFragment.kt
- map/src/main/kotlin/edu/artic/map/rendering/MapItemRenderers.kt
Follow-up to #153 . `TileOverlay` uses a different property than the `Marker`s: something called "`transparency`".
Note that this can't do anything about the way new tiles are added - that would require changes to the TileProvider, which is out of scope for now.
> Fade tile overlays in and out

- db/src/main/kotlin/edu/artic/db/AppDataManager.kt
- db/src/main/kotlin/edu/artic/db/daos/ArticObjectDao.kt
- details/src/main/kotlin/edu/artic/tours/TourDetailsStopAdapter.kt
- details/src/main/kotlin/edu/artic/tours/TourDetailsViewModel.kt
- map/src/main/kotlin/edu/artic/map/MapUtils.kt
- map/src/main/kotlin/edu/artic/map/MapViewModel.kt
- map/src/main/kotlin/edu/artic/map/carousel/TourCarouselAdapter.kt
- map/src/main/kotlin/edu/artic/map/carousel/TourCarouselViewModel.kt
This prevents tour stops with malformed or unavailable `objectId`s from being displayed on-screen.
> Disregard unseen tour stops (AIC-435)

- info/src/main/java/edu/artic/info/AccessMemberCardViewModel.kt
- info/src/main/java/edu/artic/info/InfoModule.kt
- info/src/main/java/edu/artic/info/InformationViewModel.kt
- info/src/main/java/edu/artic/info/MemberDataForbiddenException.kt
- info/src/main/java/edu/artic/info/MemberDataProvider.kt
This adds a bunch of documentation to the member api and offers friendly error messages if the build was set up incorrectly. Follow-up to #135 and #147 .
> Handle missing `Member Info API` gracefully

- map/src/main/kotlin/edu/artic/map/MapFragment.kt
- map/src/main/kotlin/edu/artic/map/MapObjects.kt
- map/src/main/kotlin/edu/artic/map/MapViewModel.kt
- map/src/main/kotlin/edu/artic/map/rendering/ObjectsMapItemRenderer.kt
- search/src/main/java/edu/artic/search/RetrofitSearchServiceProvider.kt
- viewmodel/src/main/kotlin/edu/artic/util/ObservableExtensions.kt
This adds three main fixes:
1. the location prompt screen is delayed until `mapDisplayMode` becomes well-defined.
2. object markers don't stick around in the amenities mode
3. when entering search mode, the camera is forcibly centered (not just zoomed out)
> Prevent crash from tapping an amenity (AIC-433)

- .circleci/config.yml
- app/build.gradle
- app/src/main/kotlin/edu/artic/AppModule.kt
This does not affect release builds in any significant way.
1. Determine major/minor version number and build number separately
2. In debug builds, the 'version' text on the info screen will contain more specific info
> Display real build number in debug builds

- access_card/build.gradle
- access_card/src/main/java/edu/artic/accesscard/AccessMemberCardFragment.kt
- access_card/src/main/java/edu/artic/accesscard/barcode/BarcodeEncoder.kt
- build.gradle
Updates:
- Copies the required `BarcodeEncoder` and removes `zxing-android-embedded` dependency
> Remove `zxing-android-embedded` dependency (AIC-459)

- splash/src/main/kotlin/edu/artic/splash/SplashActivity.kt
Uses `onDimissListener` instead of `positiveButtonClickListener`.
> Add OnDismissListener to splash screen's error dialog

- map/src/main/kotlin/edu/artic/map/MapFragment.kt
The `distinctUntilChanged` operator used in `switchTourRequest` stream was ignoring the events when the active tour and requested tour were same. 
FIxes the issue for following scenario.
User requests a new tour (say T1) while tour T in progress and decide to stay with T. 
Then again request same tour T1, app was not displaying the leave tour dialog.
> Show 'Leave Tour?' prompt every time we get a request to show it (AIC-519)

- localization/src/main/kotlin/edu/artic/localization/SpecifiesLanguage.kt
- localization/src/main/res/values-en/strings.xml
- localization/src/main/res/values-es/strings.xml
- localization/src/main/res/values-zh/strings.xml
- localization/src/main/res/values/strings.xml
- localization_ui/src/main/res/layout/fragment_language_settings.xml
- localization_ui/src/main/res/values/strings.xml
This covers the change in appearance of the dropdown/spinner view on the audio details screen. Previously, it showed the languages as spelled in that language (`English`, `Español`, `中文`), while now it'll show them all in the language of the application (`English`, `Spanish`, `Chinese`).
> Audio details: use app language for dropdowns (AIC-382)

- base/src/main/java/edu/artic/base/utils/StringExtensions.kt
- welcome/src/main/kotlin/edu/artic/welcome/WelcomeViewModel.kt
This ensures that the initial list of tours prefers translations of said tours into the app-wide language, if that language is not English (when it is English, the behavior is unchanged). Note that Exhibitions (`On View`) and Events do not come with translations at this time.
> Show translatable tour descriptions on home (AIC-527)

- search/src/main/java/edu/artic/search/DefaultSearchSuggestionsViewModel.kt
- search/src/main/java/edu/artic/search/SearchArtworkViewModel.kt
- search/src/main/java/edu/artic/search/SearchBaseFragment.kt
- search/src/main/java/edu/artic/search/SearchBaseViewModel.kt
- search/src/main/java/edu/artic/search/SearchExhibitionsViewModel.kt
- search/src/main/java/edu/artic/search/SearchSuggestedViewModel.kt
- search/src/main/java/edu/artic/search/SearchToursViewModel.kt
- search/src/main/res/layout/layout_cell_empty.xml
- search/src/main/res/values-es/strings.xml
- search/src/main/res/values-zh/strings.xml
- search/src/main/res/values/strings.xml
* Adds correct spacing between empty result prompt and title (AIC-515)
* underlines `visit our website` string
* Loads website when empty search result prompt is clicked. (AIC-534)
> Include link to website when no search results are found (AIC-515)

- base/src/main/java/edu/artic/base/utils/StringExtensions.kt
- details/src/main/kotlin/edu/artic/events/EventDetailFragment.kt
- details/src/main/res/layout/fragment_event_details.xml
Minor fix to the text spacing on event details screen too.
The HTML change mostly just detects newlines more-or-less in line with the swift source code.
> Improve HTML parsing on Event Details screen (AIC-414)

- db/src/main/kotlin/edu/artic/db/AppDataManager.kt
This covers cases where the first stop is not currently on view.
> Strip out unknown tour stops _before_ checking for floor numbers

- app/src/main/AndroidManifest.xml
- app/src/main/res/xml/network_security_config.xml
- base/src/main/java/edu/artic/base/utils/ViewExtensions.kt
- base/src/main/res/values/dimens.xml
- base/src/main/res/values/styles.xml
- build.gradle
- details/src/main/res/layout/fragment_event_details.xml
- events/src/main/kotlin/edu/artic/events/recyclerview/AllEventsItemDecoration.kt
- exhibitions/src/main/kotlin/edu/artic/exhibitions/recyclerview/AllToursItemDecoration.kt
- exhibitions/src/main/res/layout/cell_all_exhibitions_layout.xml
- localization_ui/src/main/res/color/info_menu_color_list.xml
- map/src/main/AndroidManifest.xml
- media/build.gradle
- media/src/main/AndroidManifest.xml
- media/src/main/java/edu/artic/media/audio/AudioPlayerService.kt
- navigation/src/main/res/values/styles.xml
- search/src/main/java/edu/artic/search/SearchBaseFragment.kt
- tours/src/main/kotlin/edu/artic/tours/recyclerview/AllToursItemDecoration.kt
- ui/src/main/kotlin/edu/artic/view/ArticMainAppBarLayout.kt
- ui/src/main/res/layout/view_app_bar_layout.xml
This covers the following changes:
* Upgrade `target` and `compile` sdks from `27` (Oreo) to `28` (Pie).
* Upgrade Exoplayer media dependency
*# from `2.8.2` to `2.9.0`
*# suppress attempts thereof to bring in older support lib dependencies
* Add explicit network security configuration
*# This currently forbids cleartext (`http://` instead of `https://`) traffic to all hosts by default
*# One exception is in place for `artic.edu`, to be removed once we receive confirmation from the server team
* Use the new `app:lineHeight` attribute to enforce specific text stylings on certain `event`- and `exhibition`-related layouts
> Update to SDK 28, fix dependencies and use lineheight

- access_card/src/main/res/drawable/sign_in_background.xml
- access_card/src/main/res/layout/layout_member_information_form.xml
- base/src/main/res/values/styles.xml
- info/src/main/res/layout/fragment_information.xml
- localization_ui/src/main/res/drawable/language_button_background.xml
- localization_ui/src/main/res/drawable/language_button_tint.xml
- localization_ui/src/main/res/drawable/language_radio_button_background.xml
- localization_ui/src/main/res/values/styles.xml
- media_ui/src/main/res/layout/activity_audio_tutorial.xml
- splash/src/main/res/drawable/splash_language_button_background.xml
- splash/src/main/res/drawable/splash_language_radio_button_background.xml
- splash/src/main/res/values/styles.xml
This adds a few more button stylings, primarily to the buttons shown on the two language selection screens (i.e. the one from the splash sequence and the one under the `info` section).
> Add pressed states to language selection screen

- base/src/main/java/edu/artic/base/utils/StringExtensions.kt
- details/src/main/kotlin/edu/artic/events/EventDetailFragment.kt
Very simple: all `ClickableSpan`s are now removed from html text.
> Remove anchor links from html (AIC-567)

- details/src/main/kotlin/edu/artic/events/EventDetailFragment.kt
- details/src/main/kotlin/edu/artic/events/EventDetailViewModel.kt
Some of our events have empty url endpoints. This makes sure buttons related to those are hidden.
> Hide button on Event Detail screen if there's no url to back it up (AIC-568)

- app/build.gradle
This is a little overdue, but ultimately it should be quite helpful. I'm keeping the manifest version code at `1000` for now - we might need to coordinate a nicer upgrade strategy in future, but for now I think we can just hard-code an offset for that property.
> Increase version number to 0.7 to mark improvements since the first 0.6.1 build

- README.md
- db/src/main/kotlin/edu/artic/db/ApiModule.kt
- db/src/main/kotlin/edu/artic/db/AppDataManager.kt
- db/src/main/kotlin/edu/artic/db/LocalAppDataServiceProvider.kt
- db/src/main/kotlin/edu/artic/db/RetrofitAppDataServiceProvider.kt
- search/src/main/java/edu/artic/search/SearchModule.kt
- search/src/main/java/edu/artic/search/SearchResultsManager.kt
- search/src/main/java/edu/artic/search/SearchServiceProvider.kt
- search/src/main/java/edu/artic/search/SearchUnavailableError.kt
- splash/src/main/kotlin/edu/artic/splash/SplashViewModel.kt
If the '.env' files are not set up right, or for that matter not defined at all, the app in its current state will crash at startup.
With these commits, a more manageable error message will be shown instead. It also adds a nice affordance to bundle a sample JSON resource with the apk, if desired.
> Prevent crashes caused by misconfiguration

- access_card/src/main/res/layout/layout_member_information_form.xml
Basically, removes `android:inputType="number"` attribute from zip code field.
> Allows entry of non-numeric characters in zip code field (AIC-574)

- db/src/main/kotlin/edu/artic/db/daos/ArticGalleryDao.kt
- db/src/main/kotlin/edu/artic/db/models/ArticObject.kt
- search/src/main/java/edu/artic/search/DefaultSearchSuggestionsViewModel.kt
- search/src/main/java/edu/artic/search/SearchArtworkViewModel.kt
- search/src/main/java/edu/artic/search/SearchBaseViewModel.kt
- search/src/main/java/edu/artic/search/SearchExhibitionsViewModel.kt
- search/src/main/java/edu/artic/search/SearchSuggestedViewModel.kt
- search/src/main/java/edu/artic/search/SearchToursViewModel.kt
Gallery label for the searched object was missing for suggested map items because the `gallery`'s value was always passed as null when instantiating ArticSearchArtworkObject. This PR changes will fetch and assign the gallery if available.
> Adds missing gallery label in artwork object details screen : (AIC-562)

- details/src/main/kotlin/edu/artic/events/EventDetailFragment.kt
> Ignore textual case on Event Details screen when comparing API text (AIC-565)

- location_ui/src/main/java/edu/artic/location/LocationPromptFragment.kt
- location_ui/src/main/java/edu/artic/map/MapFragmentExtension.kt
- location_ui/src/main/res/values/ids.xml
- map/src/main/kotlin/edu/artic/map/tutorial/TutorialFragment.kt
- map/src/main/res/layout/fragment_map.xml
When an accessibility service is active, the Map section's 'share location' and tutorial fragments are a little hard to work with. This change prevents any interaction with the `GoogleMap` while either of those are on-screen.
This does not include any changes to the 'Leave Tour' functionality.
> Prevent early access to map elements (AIC-544)

- access_card/src/main/java/edu/artic/accesscard/AccessMemberCardFragment.kt
- access_card/src/main/java/edu/artic/accesscard/AccessMemberCardViewModel.kt
- access_card/src/main/res/layout/fragment_validate_member_information.xml
- audio/src/main/res/layout/fragment_audio_lookup.xml
- events/src/main/res/layout/fragment_all_events.xml
- exhibitions/src/main/kotlin/edu/artic/exhibitions/AllExhibitionsFragment.kt
- exhibitions/src/main/kotlin/edu/artic/exhibitions/AllExhibitionsViewModel.kt
- exhibitions/src/main/res/layout/fragment_all_exhibitions.xml
- info/src/main/res/layout/fragment_museum_information.xml
- localization_ui/src/main/res/layout/fragment_language_settings.xml
- location_ui/src/main/res/layout/fragment_location_settings.xml
- map/src/main/res/layout/fragment_map.xml
- tours/src/main/res/layout/fragment_all_tours.xml
- ui/src/main/res/layout/view_app_bar_layout.xml
- ui/src/main/res/values/styles.xml
This does not significantly modify the layout of any such `ImageView`; note that this work is primarily intended to lay the groundwork for tasks related to #298 (right now, PR #291 and PR #299 are the best examples of that).
> Standardize styling of the various search icons

- app/build.gradle
- map/src/main/kotlin/edu/artic/map/SearchedObjectsAdapter.kt
The `pause` button's visibility wasn't being updated. 
Updating the visibility inside `view.post` worked.
> Fixes Play & Pause buttons overlap issue (AIC-581)

- db/src/main/kotlin/edu/artic/db/daos/ArticObjectDao.kt
- search/src/main/java/edu/artic/search/DefaultSearchSuggestionsViewModel.kt
- search/src/main/java/edu/artic/search/SearchBaseViewModel.kt
- search/src/main/java/edu/artic/search/SearchSuggestedViewModel.kt
We were expecting database would preserve the order of ids for the following sql query.
`select * from ArticObject where nid in (:ids)`
Database does not preserve the order of ids given in`IN` clause.
This PR fixes it by sorting the database result based on the input `idList`
> Map artwork ordering (AIC-586)

- db/src/main/kotlin/edu/artic/db/models/ArticTour.kt
- map/src/main/kotlin/edu/artic/map/MapConstructs.kt
- map/src/main/kotlin/edu/artic/map/MapFragment.kt
- map/src/main/kotlin/edu/artic/map/MapObjects.kt
This PR also, fix a bug where the intro tour stop isn't animated to just the selected stops.
Additionally we add an initial zoom that is slightly closer so that the departments are already loaded on the map and matching iOS
> Correct the panning behavior of the map when selecting tour stops (AIC-585, AIC-579)

- ui/src/main/kotlin/edu/artic/view/ArticMainAppBarLayout.kt
For a bit of background, we use the same immutable `Drawable` object whenever we load the resource id. This is usually just a nice memory-saving benefit of using default Resource-loading logic.
In the case of the search icons' background (defined in style `@style/Search.PrimaryScreen`, known formally as the 'wash'), this behavior is at the cause of some minor inconsistency. The wash's transparency should reflect its host fragment's scroll state.
> Stop persisting search icon's 'wash' state across sections (AIC-592)

- access_card/build.gradle
- adapter/build.gradle
- analytics/build.gradle
- app/build.gradle
- audio/build.gradle
- base/build.gradle
- build.gradle
- content_listing/build.gradle
- db/build.gradle
- details/build.gradle
- image/build.gradle
- info/build.gradle
- localization/build.gradle
- localization_ui/build.gradle
- location/build.gradle
- location_ui/build.gradle
- map/build.gradle
- media/build.gradle
- media_ui/build.gradle
- membership/build.gradle
- navigation/build.gradle
- search/build.gradle
- splash/build.gradle
- tour_manager/build.gradle
- ui/build.gradle
- viewmodel/build.gradle
- welcome/build.gradle
This is the first in what will hopefully be a series of regular maintenance changesets. This deals primarily with standardizing the 27 `build.gradle` files currently included in the repository.
While the functionality of output APKs should not be different, with any luck these changes will shed some light onto our ongoing build instability. Specific fixes for that issue are being developed at #285.
Included in this PR:
1. Update Kotlin Libs from JDK 7 variant to JDK 8 variant
2. Remove duplicate `apply plugin: X` lines from 26 `build.gradle` files
- Here's a breakdown of the duplicates:
- `com.android.library` (x1)
- `kotlin-android` (x2)
- `kotlin-android-extensions` (x24)
- `kotlin-kapt` (x25)
- Of these, only `kotlin-android-extensions` was not applied by the root `build.gradle`, so …
> Update gradle dependencies for October 2018

- app/src/main/res/drawable/ic_launcher_foreground.xml
This also leads to much lighter memory requirements on device and in Android Studio, as the vectors are no longer being rendered on such a large canvas.
> Reduce intrinsic size of adaptive icon's foreground

- app/src/test/kotlin/edu/artic/db/AppDataManagerTest.kt
This is a follow-up to some uncertainty introduced by 9d41f309997f65
> Wait for RX ops in `AppDataManagerTest` to complete before writing them off

- app/src/test/kotlin/edu/artic/db/AppDataManagerTest.kt
- build.gradle
- db/src/main/kotlin/edu/artic/db/AppDataManager.kt
- db/src/main/kotlin/edu/artic/db/AppDatabase.kt
- db/src/main/kotlin/edu/artic/db/MoshiAdapters.kt
- db/src/main/kotlin/edu/artic/db/models/ArticTour.kt
Some ArticTour objects may not come with a valid `weight` property. Until we derive a more generic solution for unexpected data formation, this will prevent issues at application startup caused by not detecting this property.
> Account for weightless tours (AIC-597)

- media/build.gradle
- media/src/main/java/edu/artic/media/audio/AudioPlayerService.kt
- tour_manager/build.gradle
- tour_manager/src/main/java/edu/artic/tours/manager/TourManagerModule.kt
- tour_manager/src/main/java/edu/artic/tours/manager/TourProgressManager.kt
* Advances tour stop when selected stop's audio translation playback ends.
> Advances tour stop when it's audio playback ends (AIC-555)

- .circleci/config.yml
- build.gradle
- gradle.properties
Ideally, this will remove some flakiness from our tests in `AppDataManagerTest.kt`.
Said uncertainty was introduced by 9d41f309997f65.
This PR also reduces the memory usage of the JVM build process (advice derived from https://discuss.circleci.com/t/circleci-2-0-android-with-kotlin/17531/2 ) and switches the version of the Android Gradle Plugin in use to the latest stable release (v3.2.1).
> Safeguard unit test threading

- map/src/main/kotlin/edu/artic/map/MapFragment.kt
`InfoWindowAdapter` was implemented incorrectly. Hidden InfoWindow was intercepting the clicks. 
Don't know why view initialized as `View(requireContext())` taking large space. When it is replaced with 
```
TextView(requireContext()).apply {
text = " "
}
```
it worked fine.
> Fixes object marker click issues (AIC-605)

- map/src/main/kotlin/edu/artic/map/MapConstructs.kt
While @caguilar187 was working on the Tour code, he increased the default zoom a little. That change was enough for departments to show up upon first load. Following some discussion thereof, we decided that this would make it harder to take in the building names and the general shape of the museum. This PR encapsulates that decision.
> Decrease map's initial zoom level just a little (AIC-604)

- map/src/main/kotlin/edu/artic/map/rendering/MapItemRenderer.kt
- map/src/main/kotlin/edu/artic/map/rendering/ObjectsMapItemRenderer.kt
- map/src/main/kotlin/edu/artic/map/rendering/TourIntroMapItemRenderer.kt
When the map is loaded in tour mode with specific tour stop, that tour stop needs to be focused. This PR adds the feature to tag the marker (the one to be focused) as the selected marker and then focus it later when created.
Fixes both AIC-584 and AIC-595.
> Map: Focuses the correct tour stop marker (AIC-584)

- app/build.gradle
- build.gradle
This was sparked by an update to the Android backport of 310 from v1.0.5 to 1.1.1. This implied an update of the main 310 library to v1.3.7 from 1.3.3, and _that_ brought the timezone data itself from the 2016j release to the 2018e one.
For release info, check out
* https://github.com/JakeWharton/ThreeTenABP/blob/master/CHANGELOG.md#version-111-2018-10-12
* https://www.threeten.org/threetenbp/changes-report.html
* various threads in http://mm.icann.org/pipermail/tz-announce/
> Update time-parsing library dependencies for November 2018

- base/src/main/res/values/styles.xml
Previously it was `textSmallest`, or 12sp on most devices.
> Increase Exhibitions' dateline text to be 16sp (AIC-588)

- base/src/main/res/values/styles.xml
- map/src/main/res/layout/fragment_map.xml
- map/src/main/res/layout/view_marker_department.xml
- map/src/main/res/layout/view_marker_text.xml
This PR
* decreases the font weight of textual markers
* center-aligns that text
* adds more vertical padding to the banner at the top of the map screen
> Adjust map marker text (AIC-591)

- base/src/main/res/drawable/ic_ticket.xml
In keeping with the skeuomorphic design of our ticket icon, I've restored the line which runs perpendicular across the icon proper. This was present in the original Swift assets but I managed to miss it in #325.
> Add perforation line to ticket icon (AIC-589)

- info/src/main/java/edu/artic/info/InfoActivity.kt
- info/src/main/res/navigation/info_navigation_graph.xml
This PR salvages some of the improvements implied by #307.
It turns out that `InfoActivity` was duplicating a bunch of logic built into the Navigation library itself....
> [Navigation] Simplify the handling of link from Welcome screen to Member Card

- app/src/main/kotlin/edu/artic/ArticApp.kt
- app/src/main/kotlin/edu/artic/CrashlyticsTree.kt
- app/src/test/kotlin/edu/artic/db/AppDataManagerTest.kt
- base/src/main/java/edu/artic/base/NetworkException.kt
- db/src/main/kotlin/edu/artic/ResultExtensions.kt
- db/src/main/kotlin/edu/artic/db/ApiModule.kt
- db/src/main/kotlin/edu/artic/db/AppDataManager.kt
- db/src/main/kotlin/edu/artic/db/RetrofitAppDataServiceProvider.kt
- splash/src/main/kotlin/edu/artic/splash/SplashActivity.kt
- splash/src/main/kotlin/edu/artic/splash/SplashViewModel.kt
* App now allows a user to proceed to the home screen irrespective of any exception type (when cached data is available) that happens during data fetching process.
* Updates the `getEvents` & `getExhibitions` method to properly check for error response.
> Properly checks if api calls error out  (AIC-594)

- welcome/src/main/kotlin/edu/artic/welcome/WelcomeFragment.kt
- welcome/src/main/res/layout/fragment_welcome.xml
- welcome/src/main/res/layout/welcome_section.xml
Follow-up to #339.
* Refactors welcome_fragment: Extracts repeating view into the `welcome_section` layout
* Hide event/exhibition section if associated data is missing.
> Reduce layout repetition in the welcome section

- base/src/main/java/edu/artic/base/utils/ViewExtensions.kt
- media_ui/src/main/java/edu/artic/media/ui/AudioDetailsFragment.kt
- media_ui/src/main/res/layout/fragment_audio_details.xml
When there is no data for `related tours` & `artist culture place`, this PR hides those sections from `audio details screen`.
> Hides empty sections in audio player details : (AIC-617)

- base/src/main/res/values/styles.xml
- info/src/main/res/layout/fragment_information.xml
- info/src/main/res/values/styles.xml
- ui/src/main/kotlin/edu/artic/ui/BaseFragment.kt
- ui/src/main/kotlin/edu/artic/view/ArticMainAppBarLayout.kt
- ui/src/main/res/layout/view_app_bar_layout.xml
- ui/src/main/res/values/attrs.xml
It is easy for a device with over 400 horizontal DPI (such as the Galaxy S8 or the Pixel 2) to not have enough space for the `Welcome` message we show to signed-in users.
The issue is slightly complicated by the `CollapsingToolbarLayout` (henceforth `CLT`) widget we've used on that screen, as it does not support the auto-size functionality available in e.g. standard `AppCompatTextView`s. For this reason, then, we needed to tie along the logic for changing the `CLT`'s size with that for changing its title.
This PR introduces a new layout attribute, a new style, and some extra calls to `ArticMainAppBarLayout` to handle the changeoff. Also of note: we need to re-establish the typeface in use on the `CTL` every time the style changes. I am not yet certain as to whether this is a bug in my …
> Shrink Main App Bars' title text (AIC-593)

- db/src/main/kotlin/edu/artic/db/AppDataManager.kt
- db/src/main/kotlin/edu/artic/db/DefaultOnDataMismatchAdapter.java
- db/src/main/kotlin/edu/artic/db/MoshiAdapters.kt
- db/src/main/kotlin/edu/artic/db/models/ArticAppData.kt
Basically, this PR replaces malformed data by null and then discards null values while updating the database. 
Handles malformed `ArticGallery, ArticObject, ArticAudioFile,ArticMapAnnotation, DashBoard, ArticMapFloor, ArticTourCategory, ArticTour, ArticExhibitionCMS` objects by adding `DefaultOnDataMismatchAdapter` for each of objects mentioned above.
> Allows optional data in json blob

- splash/src/main/kotlin/edu/artic/splash/SplashActivity.kt
Shared transition element does not work properly in Lollipop and crashes on some devices. So, the transition animation is disabled for those devices.
> Disable the transition animation in lollipop devices

- media_ui/src/main/java/edu/artic/media/ui/AudioDetailsFragment.kt
```
viewModel.credits
.map { it.isNotEmpty() }
.bindToMain(credit.visibility())
.disposedBy(disposeBag)
```
Above subscription was not working properly. Instead of using`bindToMain` operator, subscribing and updating view's visibility worked. 
```
viewModel.credits
.map { it.isNotEmpty() }
.observeOn(AndroidSchedulers.mainThread())
.subscribeBy {
credit.show(it)
}
.disposedBy(disposeBag)
```
Also, I have made sure to update the view's properties in main thread by adding `              .observeOn(AndroidSchedulers.mainThread())` wherever it was missing.
> Display object's credit line when available : AIC-646

- media_ui/src/main/java/edu/artic/media/ui/AudioDetailsViewModel.kt
- media_ui/src/main/res/layout/fragment_audio_details.xml
This changes the logic slightly: the `transcript` and `credit` ViewGroups are now visible by default. This means, of course, that we need to hide them if the current `Playable` is a Tour....
> Manually hide transcript & credit views on Tours' Audio Details screen (AIC-646)

- details/src/main/kotlin/edu/artic/exhibitions/ExhibitionDetailFragment.kt
Exhibition description is treated as html encoded string now.
> Handle html tags in exhibition description : AIC-647

- details/src/main/kotlin/edu/artic/details/DetailsActivity.kt
We only want to navigate to a specific `details` fragment if the current screen is empty.
`NavController` tries to help us by restoring its navigation state in `::onCreate`. We weren't prepared for that, so if `DetailsActivity` were recreated the app would just crash.
> Fix crash that happens while details screen is resumed from background 

- app/build.gradle
- app/src/test/kotlin/edu/artic/db/AppDataManagerTest.kt
- app/src/test/kotlin/edu/artic/splash/ErrorMessagePresenterTest.kt
My best guess is that the reflection logic in `mockito-kotlin:1.5.0` was not forward-compatible with `Kotlin 1.3.31`.
> Update to latest Mockito-Kotlin (2.1.0) to fix test execution

- localization/src/main/kotlin/edu/artic/localization/SpecifiesLanguage.kt
- media/src/main/java/edu/artic/media/audio/AudioPlayerService.kt
- media_ui/src/main/java/edu/artic/media/ui/AudioDetailsViewModel.kt
The implementation of `SpecifiesLanguage::underlyingLocale()` will throw a NullPointerException if the `SpecifiesLanguage` object in question doesn't have a language. This PR simply returns the `Locale.ROOT`constant from that method in such a scenario, but realistically we shouldn't even allow the creation of objects without a defined language.
I've been working on a more holistic solution to this problem in a separate branch - `pc-better-active-audio-file-guarantees` - but I haven't scoped out the implications of showing a language selector on the tour intro page yet. Regardless, this PR should be fully capable of working around the crashes.
@caguilar187 I'd like you to review. I think we need to discuss whether there might be an alternative to the current use of `EMPTY_AUDIO_FILE` in …
> Avoid parsing null language tags (AIC-652)

- media/src/main/java/edu/artic/media/audio/AudioPlayerService.kt
Before, we restricted playback to the earpiece at exclusion of all other connections (c.f. `AIC-271`, `AIC-272`, #218 ). It turned out that didn't work so well when headphones were plugged in, so we're disabling the behavior.
> Permit system control of audio (AIC-651)

- welcome/src/main/kotlin/edu/artic/welcome/WelcomeViewModel.kt
This commit fixes an issue where the messages screen appears even if there are no launchMessages to present.
> Fix empty messages screen issue

- localization_ui/src/main/java/edu/artic/localization/ui/LanguageSettingsFragment.kt
When this project was originally written, the version of the `Fragment` class that was used couldn't have a null `arguments` property; it would be an empty `Bundle` if no arguments were passed when the Fragment was created. The newer `Fragment` class's `arguments` is null if no arguments were passed, however, so now we need to check for null `arguments` and return false.
Before:
https://github.com/user-attachments/assets/e0c277ec-55ef-4085-bd85-1d2944455d72
After:
https://github.com/user-attachments/assets/0cc14855-2b6f-4527-bcc5-efb01aecc42f
> Fix: Handle null arguments in Language Settings fragment

- info/src/main/java/edu/artic/info/MuseumInformationViewModel.kt
- info/src/main/res/layout/fragment_museum_information.xml
- info/src/main/res/values-en/strings.xml
- info/src/main/res/values-es/strings.xml
- info/src/main/res/values-fr/strings.xml
- info/src/main/res/values-ko/strings.xml
- info/src/main/res/values-zh/strings.xml
- info/src/main/res/values/strings.xml
This PR adds localized strings for the museum hours field in the Museum Information screen for all languages. But since the CMS field is still populated for at least some languages, we'll continue to use that via the view binding if and only if it's not a blank string.
Before (e.g. Spanish):
After:
> Fix: Add localized strings for museum hours

- db/schemas/edu.artic.db.AppDatabase/13.json
- db/src/main/kotlin/edu/artic/db/ApiBodyGenerator.kt
- db/src/main/kotlin/edu/artic/db/AppDatabase.kt
- db/src/main/kotlin/edu/artic/db/models/ArticEvent.kt
- details/src/main/kotlin/edu/artic/events/EventDetailFragment.kt
- details/src/main/kotlin/edu/artic/events/EventDetailViewModel.kt
- details/src/main/res/layout/fragment_event_details.xml
This PR implements the new conditional logic to support restricted ticketed events, using the new ticket sale and button caption properties. We follow roughly the same UI treatment as [iOS](https://github.com/art-institute-of-chicago/aic-mobile-ios/pull/63), placing the button caption centered between the button, if present, and the event description.
Before:
After:
> Feature: Handle restricted ticketed events

- db/src/main/kotlin/edu/artic/db/AppDataManager.kt
One of the outdated dependencies that was updated [in this PR](https://github.com/art-institute-of-chicago/aic-mobile-android/pull/382/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R14) was Room, the database framework that our app uses to persist the CMS content to disk and populate the app. As it turns out, that update turned an old migration-enabling workaround into a migration-stopping bug! Fortunately, the fix was as simple as doing exactly what the comment said to do and removing the workaround. Thanks, past developer. 👍
> Remove old Room database migration workaround 

- map/build.gradle
- map/src/main/kotlin/edu/artic/map/MapConstructs.kt
- map/src/main/kotlin/edu/artic/map/MarkerGenerators.kt
- map/src/main/kotlin/edu/artic/map/rendering/BaseMapTileProvider.kt
- map/src/main/kotlin/edu/artic/map/rendering/GlideMapTileProvider.kt
- map/src/main/res/values-v35/styles.xml
This PR increases the maximum zoom of our map, allowing it to fetch the new zoom level 6 tiles. Note that Google Maps SDK technically allows a max zoom of 22 (even though Google won't let us use it today 🫠 ), while we set our max to just _under_ 22. This is because if we actually could reach 22 then the app would request zoom level 7 tiles, which aren't available. I also slightly adjusted the bounds of the tiles at zoom level 6 to better line them up with the real latitude and longitude values of the rooms and objects in the museum.
There are also two bug fixes for map-related crashes that are reported in the current production app:
1.  We use a third party library called [CircleImageView](https://github.com/hdodenhof/CircleImageView) to render our map markers. There was sometimes a crash …
> Feature: Update map zoom

- audio/src/main/res/color/audio_menu_color_list.xml
- base/src/main/res/color/menu_color_list.xml
- base/src/main/res/values/colors.xml
- info/src/main/res/color/info_menu_color_list.xml
- map/src/main/res/color/map_menu_color_list.xml
- navigation/src/main/res/values/styles.xml
This PR updates the colors that we apply to the navigation bar and its items to match the styling of the iOS app. Many of the colors were already defined in the app's resources under different names, so I've just added aliases and grouped them together to make it clear how they're used. 
https://github.com/user-attachments/assets/11d95b50-d132-4a0a-ae46-85be06145f93
> Feature: Update navigation bar colors
