- welcome/src/main/res/layout/app_bar_layout.xml
Displays the title of the expanded toolbar in the center.
> [Toolbar] - Centers the tooblar title when expanded

- app/build.gradle
- app/src/main/kotlin/edu/artic/ArticApp.kt
- base/src/main/java/edu/artic/base/utils/DateTimeHelper.kt
- db/src/main/kotlin/edu/artic/db/AppConverters.kt
- db/src/main/kotlin/edu/artic/db/MoshiAdapters.kt
- db/src/main/kotlin/edu/artic/db/daos/ArticEventDao.kt
- db/src/main/kotlin/edu/artic/db/models/ArticEvent.kt
- welcome/src/main/kotlin/edu/artic/welcome/WelcomeViewModel.kt
Sorts the events summary by the start date.
> [Events] - Sorts events by start date

- db/src/main/kotlin/edu/artic/db/AppDataManager.kt
- db/src/main/kotlin/edu/artic/db/AppDatabase.kt
- db/src/main/kotlin/edu/artic/db/daos/ArticEventDao.kt
- db/src/main/kotlin/edu/artic/db/daos/ArticExhibitionCMSDao.kt
- db/src/main/kotlin/edu/artic/db/daos/ArticExhibitionDao.kt
- db/src/main/kotlin/edu/artic/db/daos/ArticTourDao.kt
- db/src/main/kotlin/edu/artic/db/models/ArticAppData.kt
- db/src/main/kotlin/edu/artic/db/models/ArticEvent.kt
- db/src/main/kotlin/edu/artic/db/models/ArticExhibition.kt
- db/src/main/kotlin/edu/artic/db/models/ArticExhibitionCMS.kt
Reconciles the exhibitions using JSON blob's exhibitions.
> [Exhibitions] - Reconciles exhibitions to cms exhibitions

- base/src/main/java/edu/artic/base/utils/DateTimeHelper.kt
- db/src/main/kotlin/edu/artic/db/daos/ArticEventDao.kt
- events/src/main/kotlin/edu/artic/events/AllEventsAdapter.kt
- events/src/main/kotlin/edu/artic/events/AllEventsFragment.kt
- events/src/main/kotlin/edu/artic/events/AllEventsViewModel.kt
- events/src/main/kotlin/edu/artic/events/recyclerview/AllEventsItemDecoration.kt
- events/src/main/res/layout/cell_all_events_layout.xml
- events/src/main/res/values/dimens.xml
I don't fully like this implementation but can't think of anything to update it with. Might come back to refactor this code at a later date
> [AllEvents] update view to dated section headers (AIC-203)

- LICENSE
This file matches that used by the ios codebase.
> [Documentation] - add an explicit AGPL v3 license

- audio/src/main/java/edu/artic/audio/AudioActivity.kt
- audio_ui/src/main/java/edu/artic/audioui/AudioUiModule.kt
- audio_ui/src/main/java/edu/artic/audioui/BottomAudioPlayerFragment.kt
- audio_ui/src/main/java/edu/artic/audioui/NarrowAudioPlayerFragment.kt
- audio_ui/src/main/java/edu/artic/audioui/NarrowAudioPlayerViewModel.kt
- map/src/main/kotlin/edu/artic/map/MapActivity.kt
- map/src/main/kotlin/edu/artic/map/MapObjectDetailsFragment.kt
- map/src/main/res/layout/activity_map.xml
- media/src/main/java/edu/artic/media/audio/AudioPlayerService.kt
- welcome/src/main/res/layout/activity_welcome.xml
This includes renames of two files.
> Update audio docs to better reflect the current structure

- README.md
Fix a minor typo/phrasing error
> [Documentation] Update README.md

- MODULES.md
Clean up some minor inconsistencies regarding use of the terms "DAO" and "objet d'art"
> [Documentation] Update MODULES.md

- base/src/main/res/values/strings.xml
- map/src/main/kotlin/edu/artic/map/MapFragment.kt
- map/src/main/kotlin/edu/artic/map/MapViewModel.kt
- map/src/main/kotlin/edu/artic/map/carousel/TourCarouselFragment.kt
- map/src/main/kotlin/edu/artic/map/carousel/TourCarouselViewModel.kt
- map/src/main/kotlin/edu/artic/map/carousel/TourProgressManager.kt
- map/src/main/res/values/styles.xml
-  Refactors how map loads display mode
- Adds Leave Tour UI Dialog (styles has been implemented yet)
> [Tour] - Adds Leave tour feature

- base/src/main/res/values/colors.xml
- db/build.gradle
- db/src/main/kotlin/edu/artic/ui/util/UrlExtension.kt
- map/src/main/kotlin/edu/artic/map/GoogleMapUtil.kt
- map/src/main/kotlin/edu/artic/map/MapActivity.kt
- map/src/main/kotlin/edu/artic/map/MapFragment.kt
- map/src/main/kotlin/edu/artic/map/MapItem.kt
- map/src/main/kotlin/edu/artic/map/MarkerGenerators.kt
- map/src/main/kotlin/edu/artic/map/helpers/ArticObjectExtension.kt
- map/src/main/kotlin/edu/artic/map/helpers/CollectionExtensions.kt
- map/src/main/kotlin/edu/artic/map/util/BiasedPair.kt
- ui/build.gradle
This greatly reduces the number of duplicate requests.
> Map: restrict which objects load

- search/src/main/java/artic/edu/search/SearchActivity.kt
- search/src/main/java/artic/edu/search/SearchViewModel.kt
- search/src/main/res/drawable/ic_close.xml
- search/src/main/res/layout/search_app_bar_layout.xml
* adds clear icon to toolbar
* clears the search text when clear icon is pressed
* sends analytics event when clear icon is pressed
> Clear Search Text

- db/src/main/kotlin/edu/artic/db/AppDataManager.kt
- db/src/main/kotlin/edu/artic/db/Constants.kt
- db/src/main/kotlin/edu/artic/db/MoshiAdapters.kt
- db/src/main/kotlin/edu/artic/db/models/ArticGallery.kt
- db/src/main/kotlin/edu/artic/db/models/ArticTour.kt
* resolves #74 
* converts string floor to int in gallery and tour
> Floor serialization

- audio/src/main/java/edu/artic/audio/AudioLookupFragment.kt
This event is sent _before_ the new track starts playing.
> Report an event whenever a new track is keyed in (AIC-146)

- map/src/main/kotlin/edu/artic/map/MapFragment.kt
- map/src/main/kotlin/edu/artic/map/MapViewModel.kt
Updates:
* Displays leave tour confirmation dialog
* Ends the tour display mode when a user confirms to leave the tour
> Leave tour

- base/src/main/java/edu/artic/base/PreferencesManager.kt
- base/src/main/res/values/strings.xml
- db/src/main/kotlin/edu/artic/db/models/ArticTour.kt
- localization/src/main/kotlin/edu/artic/localization/LanguageSelector.kt
- localization/src/main/kotlin/edu/artic/localization/LocalizationPreferences.kt
- map/src/main/kotlin/edu/artic/map/carousel/TourCarouselViewModel.kt
- map/src/main/res/layout/tour_carousel_intro_cell.xml
- tours/src/main/kotlin/edu/artic/tours/TourDetailsFragment.kt
- tours/src/main/kotlin/edu/artic/tours/TourDetailsStopAdapter.kt
- tours/src/main/kotlin/edu/artic/tours/TourDetailsViewModel.kt
- tours/src/main/res/layout/fragment_tour_details.xml
Updates:
* Changes the tour details when the tour language is changed
* Saves/restores user selected tour language when a tour is started/resumed
* Prioritizes tour locale over app locale on tour related screens
> Tour translation

- db/src/main/kotlin/edu/artic/db/Constants.kt
- db/src/main/kotlin/edu/artic/db/models/ArticTour.kt
- map/src/main/kotlin/edu/artic/map/MapActivity.kt
- map/src/main/kotlin/edu/artic/map/MapConstructs.kt
- map/src/main/kotlin/edu/artic/map/MapFragment.kt
- map/src/main/kotlin/edu/artic/map/MapViewModel.kt
- map/src/main/kotlin/edu/artic/map/carousel/TourCarouselFragment.kt
- map/src/main/kotlin/edu/artic/map/carousel/TourCarouselViewModel.kt
- tours/src/main/kotlin/edu/artic/tours/TourDetailsFragment.kt
- tours/src/main/kotlin/edu/artic/tours/TourDetailsViewModel.kt
Updates:
* Starts the tour at the desired tour stop.
* Animates the map to the tour stop's location
* Tour Carousel selects the selected stop as the initial page
> Tour start stop

- base/src/main/res/values/strings.xml
- map/src/main/kotlin/edu/artic/map/MapFragment.kt
- map/src/main/kotlin/edu/artic/map/MapViewModel.kt
Updates:
* Displays leave current prompt if the user starts a new tour when one is already in progress
> Support switching tours

- .idea/navEditor.xml
- search/src/main/java/artic/edu/search/ApiSearchResult.kt
- search/src/main/java/artic/edu/search/ArticSearchResult.kt
- search/src/main/java/artic/edu/search/SearchFragment.kt
- search/src/main/java/artic/edu/search/SearchModule.kt
- search/src/main/java/artic/edu/search/SearchResultCellViewModels.kt
- search/src/main/java/artic/edu/search/SearchResultsAdapter.kt
- search/src/main/java/artic/edu/search/SearchResultsFragment.kt
- search/src/main/java/artic/edu/search/SearchResultsManager.kt
- search/src/main/java/artic/edu/search/SearchResultsPagerAdapter.kt
- search/src/main/java/artic/edu/search/SearchResultsSuggestedFragment.kt
- search/src/main/java/artic/edu/search/SearchResultsSuggestedViewModel.kt
- search/src/main/java/artic/edu/search/SearchResultsViewModel.kt
- search/src/main/java/artic/edu/search/SearchViewModel.kt
- search/src/main/res/layout/fragment_search_results.xml
- search/src/main/res/layout/fragment_search_results_sub.xml
- search/src/main/res/navigation/search_navigation_graph.xml
- search/src/main/res/navigation/search_sub_navigation_graph.xml
Basically boilerplate code to be used for search.
> Basic UI work for search

- map/src/main/kotlin/edu/artic/map/MapViewModel.kt
- map/src/main/kotlin/edu/artic/map/carousel/TourCarouselViewModel.kt
Updates
* plays tour intro in selected tour language
* plays tour stops in selected tour language
> Fixes Tour Stop audio translation 

- map/src/main/kotlin/edu/artic/map/MapFragment.kt
- media/src/main/java/edu/artic/media/audio/AudioPlayerService.kt
- media_ui/src/main/java/edu/artic/media/ui/NarrowAudioPlayerFragment.kt
Updates:
* Stops the current audio translation track
* Closes the narrow audio player upon leaving tour
> [Tour] - Stops/closes narrow the audio player upon leaving the tour

- db/src/main/kotlin/edu/artic/db/ApiBodyGenerator.kt
- db/src/main/kotlin/edu/artic/db/RetrofitAppDataServiceProvider.kt
- db/src/main/kotlin/edu/artic/db/models/ApiSearchResult.kt
- db/src/main/kotlin/edu/artic/db/models/ArticSearchObject.kt
- search/src/main/java/artic/edu/search/ObservableExtensions.kt
- search/src/main/java/artic/edu/search/RetrofitSearchServiceProvider.kt
- search/src/main/java/artic/edu/search/SearchApi.kt
- search/src/main/java/artic/edu/search/SearchServiceProvider.kt
This adds a `loadAllContent` call to the `SearchApi`. Not ready for primetime, but it does....well, _something_.
> Search query for results (AIC-345)

- analytics/src/main/java/edu/artic/analytics/ScreenConstants.kt
- map/src/main/kotlin/edu/artic/map/MapViewModel.kt
Adds tour started and left analytic events.
> Tour analytics

- map/src/main/kotlin/edu/artic/map/MapActivity.kt
- map/src/main/kotlin/edu/artic/map/MapFragment.kt
- map/src/main/kotlin/edu/artic/map/MapModule.kt
- map/src/main/kotlin/edu/artic/map/MapViewModel.kt
- map/src/main/kotlin/edu/artic/map/SearchManager.kt
- map/src/main/kotlin/edu/artic/map/SearchObjectDetailsFragment.kt
- map/src/main/kotlin/edu/artic/map/SearchObjectDetailsViewModel.kt
- map/src/main/kotlin/edu/artic/map/carousel/TourCarouselFragment.kt
- map/src/main/kotlin/edu/artic/map/rendering/MapItemRenderers.kt
- map/src/main/kotlin/edu/artic/map/rendering/ObjectsMapItemRenderer.kt
- map/src/main/res/layout/fragment_search_object_details.xml
- navigation/src/main/java/edu/artic/navigation/NavigationConstants.kt
- search/src/main/java/artic/edu/search/DefaultSearchSuggestionsFragment.kt
- tours/src/main/kotlin/edu/artic/tours/TourDetailsFragment.kt
This work basically includes loading the default suggested map items to map.
> [Feature] Loads the searched object in the map

- map/src/main/kotlin/edu/artic/map/MapFragment.kt
- map/src/main/kotlin/edu/artic/map/MapViewModel.kt
* Closes the tour carousel on leaving the tour
* Clears out the searched object from the cache when the map display mode is changed
> [Tour] - Closes the tour carousel on leaving tour

- search/src/main/java/artic/edu/search/ArticSearchResult.kt
- search/src/main/java/artic/edu/search/SearchBaseFragment.kt
- search/src/main/java/artic/edu/search/SearchDividerItemDecoration.kt
- search/src/main/java/artic/edu/search/SearchExhibitionsViewModel.kt
- search/src/main/java/artic/edu/search/SearchFragment.kt
- search/src/main/java/artic/edu/search/SearchResultCellViewModels.kt
- search/src/main/java/artic/edu/search/SearchResultsAdapter.kt
- search/src/main/java/artic/edu/search/SearchResultsManager.kt
- search/src/main/java/artic/edu/search/SearchSuggestedViewModel.kt
- search/src/main/java/artic/edu/search/SearchViewModel.kt
- search/src/main/res/drawable/divider_search.xml
- search/src/main/res/layout/layout_cell_search_list_item.xml
- search/src/main/res/layout/search_app_bar_layout.xml
Ui and minor functionality updates to suggested page
> Search Suggest

- db/src/main/kotlin/edu/artic/db/AppDatabase.kt
- db/src/main/kotlin/edu/artic/db/daos/ArticMapFloorDao.kt
- db/src/main/kotlin/edu/artic/db/models/ArticAppData.kt
- db/src/main/kotlin/edu/artic/db/models/ArticMapFloor.kt
- map/src/main/kotlin/edu/artic/map/MapFragment.kt
- map/src/main/kotlin/edu/artic/map/MapViewModel.kt
- map/src/main/kotlin/edu/artic/map/rendering/BaseMapTileProvider.kt
- map/src/main/kotlin/edu/artic/map/rendering/GlideMapTileProvider.kt
Pull base url from MapFloor object
> Map Tile Generation

- .idea/navEditor.xml
- audio/src/main/AndroidManifest.xml
- info/src/main/AndroidManifest.xml
- map/src/main/AndroidManifest.xml
- search/src/main/AndroidManifest.xml
- splash/src/main/AndroidManifest.xml
- welcome/src/main/AndroidManifest.xml
Update all manifests to use portrait screen orientation
> Screen Orientation (AIC-354)

- search/src/main/java/edu/artic/search/SearchResultsContainerFragment.kt
- search/src/main/res/layout/fragment_search_results.xml
- search/src/main/res/layout/tab_search_result_container.xml
Update ui for search headers (suggested, artworks, tours, exhibitions)
> Improved search header appearance (AIC-378)

- map/src/main/kotlin/edu/artic/map/MapFragment.kt
[Map] fix crash caused by background thread... seems we keep losing this change
> Fix crash by reacting to floor changes on Main Thread

- info/src/main/res/layout/fragment_information.xml
- info/src/main/res/values/strings.xml
- ui/src/main/kotlin/edu/artic/view/ArticMainAppBarLayout.kt
- ui/src/main/res/layout/view_app_bar_layout.xml
- ui/src/main/res/values/attrs.xml
Adds subtitle to app bar layout.
> App bar subtitle [AIC-63]

- base/src/main/res/values/styles.xml
- location/src/main/java/edu/artic/location/LocationModule.kt
- location/src/main/java/edu/artic/location/LocationPromptFragment.kt
- location/src/main/java/edu/artic/location/LocationPromptViewModel.kt
- location/src/main/java/edu/artic/location/LocationService.kt
- location/src/main/res/drawable/button_not_now.xml
- location/src/main/res/layout/fragment_location_prompt.xml
- location/src/main/res/values/strings.xml
- map/build.gradle
- map/src/main/kotlin/edu/artic/map/MapActivity.kt
- map/src/main/kotlin/edu/artic/map/MapFragment.kt
- map/src/main/kotlin/edu/artic/map/MapViewModel.kt
- map/src/main/res/navigation/map_navigation_graph.xml
Shows a prompt unless location permission has been requested
> Map Location Prompt (AIC-77)

- base/src/main/res/drawable/ic_search_24dp.xml
- info/src/main/java/edu/artic/info/AccessMemberCardFragment.kt
- info/src/main/res/layout/fragment_information.xml
- info/src/main/res/navigation/info_navigation_graph.xml
- info/src/main/res/values/strings.xml
- map/src/main/kotlin/edu/artic/map/carousel/TourCarouselFragment.kt
- navigation/src/main/java/edu/artic/navigation/NavigationConstants.kt
- ui/src/main/kotlin/edu/artic/ui/BaseFragment.kt
- welcome/src/main/kotlin/edu/artic/welcome/WelcomeFragment.kt
- welcome/src/main/kotlin/edu/artic/welcome/WelcomeViewModel.kt
Presents member card when user taps access your member card link in welcome screen
> [Welcome] - Launches access member card from home screen [AIC-444]

- info/build.gradle
Reverts art-institute-of-chicago/aic-mobile-android#142
> Revert "[Gradle] update gradle to pull varaibles from local.properties"

- db/src/main/kotlin/edu/artic/db/ApiModule.kt
- info/build.gradle
- info/src/main/java/edu/artic/info/InfoActivity.kt
- info/src/main/res/navigation/info_navigation_graph.xml
- info/src/main/res/values/strings.xml
Updates:
* Removes url verification code
* Removes unused depdency
* Fixes `welcome -> access member card` navigation issue
> Membership endpoint update

- info/src/main/java/edu/artic/info/AccessMemberCardFragment.kt
- info/src/main/java/edu/artic/info/LanguageSettingsViewModel.kt
- info/src/main/res/values-es/strings.xml
- info/src/main/res/values-zh/strings.xml
- info/src/main/res/values/strings.xml
*  Adds language selected analytics event
*  Adds `Expires` label for membership expiration date
> Analytics : Language Selected (AIC-467)

- db/src/main/kotlin/edu/artic/db/AppDataManager.kt
- db/src/main/kotlin/edu/artic/db/AppDatabase.kt
- db/src/main/kotlin/edu/artic/db/models/ArticTour.kt
- details/src/main/kotlin/edu/artic/tours/TourDetailsStopAdapter.kt
- map/src/main/kotlin/edu/artic/map/carousel/TourCarouselAdapter.kt
Now we actually save the result of filtering these stops.
> Save filtered tour stops to db (AIC-435)

- info/src/main/res/values-en/strings.xml
- info/src/main/res/values-es/strings.xml
- info/src/main/res/values-zh/strings.xml
- info/src/main/res/values/strings.xml
- membership/src/main/java/edu/artic/membership/AccessMemberCardFragment.kt
- membership/src/main/res/values-es/strings.xml
- membership/src/main/res/values-zh/strings.xml
- membership/src/main/res/values/strings.xml
Rather simple stuff. I think this was just a minor oversight from #163 .
> Move some strings from :info module to :membership module

- splash/src/main/kotlin/edu/artic/splash/SplashActivity.kt
Updates
* Fades in welcome text
> Fades in welcome text [AIC-463]

- splash/src/main/kotlin/edu/artic/splash/SplashActivity.kt
- splash/src/main/res/layout/activity_splash.xml
Fixes the progress bar on smaller screens. Using linearlayout for ease.
> Improve appearance of Splash on small screens

- membership/src/main/java/edu/artic/membership/AccessMemberCardFragment.kt
- membership/src/main/java/edu/artic/membership/AccessMemberCardViewModel.kt
- membership/src/main/res/values-en/strings.xml
- membership/src/main/res/values-es/strings.xml
- membership/src/main/res/values-zh/strings.xml
Updates:
* Adds hints for `zipCode` and `memberID` field in access member card screen
> Access member form hints [AIC-471]

- search/src/main/java/edu/artic/search/SearchActivity.kt
- search/src/main/java/edu/artic/search/SearchFragment.kt
- search/src/main/java/edu/artic/search/SearchResultsManager.kt
This adds some docs to search-related classes and fixes a simple crash.
> Prevent search screen crash (AIC-488)

- map/src/main/kotlin/edu/artic/map/MapFragment.kt
Wasn't using the `MapItemModel` when `setOnMarkerClickListener` was called
> Fix an issue where the map fragment did not select artwork properly

- access_card/src/main/res/values-en/strings.xml
- access_card/src/main/res/values/strings.xml
- base/src/main/java/edu/artic/base/NetworkException.kt
- base/src/main/res/values/strings.xml
- splash/src/main/kotlin/edu/artic/splash/SplashActivity.kt
- splash/src/main/res/values/styles.xml
- viewmodel/src/main/kotlin/edu/artic/util/ObservableExtensions.kt
Updates:
* Fixes app crash during app data download (handles network exceptions)
* Refactors the splash logic of handling error
> Handle Network Exceptions during app startup (AIC-480)

- localization_ui/src/main/java/edu/artic/localization/ui/LanguageSettingsFragment.kt
- localization_ui/src/main/java/edu/artic/localization/ui/LanguageSettingsViewModel.kt
- splash/src/main/kotlin/edu/artic/splash/SplashActivity.kt
* Currently, there is a bug in language selection dialog where the user has to click twice to dismiss it. This pull req fixes the issue.
* Adds alpha animation to dialog before it is dismissed
> [Issue] Fixes Language Selection Dialog Dismissal Issue

- db/src/main/kotlin/edu/artic/db/AppDataPreferencesManager.kt
- splash/src/main/kotlin/edu/artic/splash/SplashActivity.kt
- splash/src/main/kotlin/edu/artic/splash/SplashViewModel.kt
Updates :
- app will serve cached data to the user when network request for fetching the data fails.
> Serve cached data if app starts up offline (AIC-486)

- splash/src/main/kotlin/edu/artic/splash/SplashActivity.kt
Wrong execption type `NetworkErrorException` was used instead of `NetworkException`.
> Proceed To Home Screen when Network Error (when cache is available)

- base/src/main/java/edu/artic/base/utils/ActivityExtensions.kt
- map/src/main/kotlin/edu/artic/map/MapFragment.kt
Checks for permission before displaying the location permission prompt.
> Do not display location prompt if location permission is already granted (AIC-518)

- MODULES.md
- map/src/main/kotlin/edu/artic/map/rendering/GlideMapTileProvider.kt
- map/tiler.sh
Also load the default tile and use it for instances where it is required instead of loading from assets everytime
> Add the tiler.sh to version control

- db/src/main/kotlin/edu/artic/db/AppDatabase.kt
- db/src/main/kotlin/edu/artic/db/models/ApiSearchResult.kt
> Add support for artwork results without 'artist_title'

- base/src/main/res/values/dimens.xml
- db/src/main/kotlin/edu/artic/db/models/ArticSearchArtworkObject.kt
- events/src/main/kotlin/edu/artic/events/AllEventsFragment.kt
- exhibitions/src/main/kotlin/edu/artic/exhibitions/AllExhibitionsFragment.kt
- info/src/main/java/edu/artic/info/MuseumInformationFragment.kt
- info/src/main/java/edu/artic/info/MuseumInformationViewModel.kt
- localization_ui/src/main/java/edu/artic/localization/ui/LanguageSettingsFragment.kt
- location_ui/src/main/java/edu/artic/location/InfoLocationSettingsFragment.kt
- location_ui/src/main/java/edu/artic/location/InfoLocationSettingsViewModel.kt
- map/src/main/kotlin/edu/artic/map/MapFragment.kt
- map/src/main/kotlin/edu/artic/map/MapViewModel.kt
- map/src/main/kotlin/edu/artic/map/helpers/ArticObjectExtension.kt
- map/src/main/kotlin/edu/artic/map/rendering/MapItemModel.kt
- map/src/main/kotlin/edu/artic/map/rendering/ObjectsMapItemRenderer.kt
- map/src/main/res/layout/fragment_map.xml
- search/src/main/java/edu/artic/search/SearchAudioDetailViewModel.kt
- search/src/main/java/edu/artic/search/SearchResultsAdapter.kt
- tours/src/main/kotlin/edu/artic/tours/AllToursFragment.kt
This pull request resolves the following issues:
AIC-266 Search Button is Not Visible on Map 
AIC-479 Search Button Does Nothing
AIC-494 Show on Map via search should show gallery for object without audio
> All instances of the search icon now work and artworks with a gallery go to map

- details/src/main/kotlin/edu/artic/tours/TourDetailsFragment.kt
- info/src/main/java/edu/artic/info/InfoActivity.kt
- map/src/main/kotlin/edu/artic/map/MapObjects.kt
- media_ui/src/main/java/edu/artic/media/ui/AudioDetailsFragment.kt
- navigation/src/main/java/edu/artic/navigation/NavigationSelectListener.kt
- search/src/main/AndroidManifest.xml
- ui/src/main/kotlin/edu/artic/ui/BaseActivity.kt
- welcome/src/main/kotlin/edu/artic/welcome/WelcomeActivity.kt
[AIC-539] Hide Audio Guide Translation If Only 1 Available
[AIC-525] Tapping Category Tap Should Clear Screen History
[AIC-498] Selecting Search Icon Should Display Keyboard
[AIC-528] Increase default map tilt angle, and straighten
Ensure a locale is set on first launch
> Navigation issues, between Search and the main activities, and between home and secondary tabs

- base/build.gradle
- db/src/main/kotlin/edu/artic/db/AppConverters.kt
- db/src/main/kotlin/edu/artic/db/models/ArticEvent.kt
- db/src/main/kotlin/edu/artic/db/models/ArticExhibition.kt
- details/src/main/kotlin/edu/artic/events/EventDetailViewModel.kt
- details/src/main/kotlin/edu/artic/exhibitions/ExhibitionDetailViewModel.kt
- events/src/main/kotlin/edu/artic/events/AllEventsViewModel.kt
- exhibitions/src/main/kotlin/edu/artic/exhibitions/AllExhibitionsViewModel.kt
- localization/src/main/kotlin/edu/artic/localization/util/DateTimeHelper.kt
- welcome/src/main/kotlin/edu/artic/welcome/WelcomeViewModel.kt
- welcome/src/main/res/layout/fragment_welcome.xml
- welcome/src/main/res/layout/welcome_on_view_cell_layout.xml
This also moves `DateTimeHelper.kt` to the localization module, in keeping with its language-dependent behaviors.
> Address some home-screen concerns relevant to smaller screens (AIC-401)

- map/src/main/kotlin/edu/artic/map/carousel/TourCarouselAdapter.kt
- search/src/main/java/edu/artic/search/SearchAudioDetailFragment.kt
Updates:
* adds placeholder image in search audio object screen
* adds placeholder image in tour carousel
> Add missing placeholders to audio details screen (AIC-360)

- info/src/main/res/layout/fragment_information.xml
- info/src/main/res/values/styles.xml
- ui/src/main/kotlin/edu/artic/view/ArticMainAppBarLayout.kt
- ui/src/main/res/layout/view_app_bar_layout.xml
- ui/src/main/res/values/attrs.xml
Updates:
* Fixes design issues in information screen.
> Update design of Information section (AIC-499)

- base/src/main/res/values/styles.xml
- exhibitions/src/main/kotlin/edu/artic/exhibitions/AllExhibitionsFragment.kt
- exhibitions/src/main/kotlin/edu/artic/exhibitions/recyclerview/AllToursItemDecoration.kt
- exhibitions/src/main/res/layout/cell_all_exhibitions_layout.xml
- exhibitions/src/main/res/layout/fragment_all_exhibitions.xml
- exhibitions/src/main/res/values/dimens.xml
This is mostly a matter of correcting some fonts and reducing vertical spacing between cells.
> On View/All Exhibitions Screen: style fixes (AIC-408)

- base/src/main/java/edu/artic/base/utils/ResourcesExtensions.kt
- base/src/main/res/values/styles.xml
- details/src/main/kotlin/edu/artic/tours/TourDetailsFragment.kt
- details/src/main/kotlin/edu/artic/tours/TourDetailsStopAdapter.kt
- details/src/main/kotlin/edu/artic/tours/TourDetailsViewModel.kt
- details/src/main/res/drawable/tour_detail_tour_stop_divider.xml
- details/src/main/res/layout/cell_tour_details_stop.xml
- details/src/main/res/layout/fragment_tour_details.xml
- details/src/main/res/values/colors.xml
- details/src/main/res/values/strings.xml
- map/src/main/kotlin/edu/artic/map/carousel/TourCarouselAdapter.kt
- media_ui/src/main/res/drawable/ic_language_caret.xml
- search/src/main/java/edu/artic/search/SearchDividerItemDecoration.kt
- ui/src/main/kotlin/edu/artic/ui/SizedColorDrawable.kt
This adds some missing icons and updates the amount of space around text to try to match our design requirements.
We also now have two new utilities:
* a method to convert dp to pixels
* a `ColorDrawable` subclass that can be locked to positive intrinsic dimensions
> Tour Details Screen style fixes (AIC-405)

- base/src/main/res/values/styles.xml
- details/src/main/kotlin/edu/artic/exhibitions/ExhibitionDetailFragment.kt
- details/src/main/kotlin/edu/artic/exhibitions/ExhibitionDetailViewModel.kt
- details/src/main/res/layout/fragment_exhibition_details.xml
- exhibitions/src/main/res/layout/cell_all_exhibitions_layout.xml
This corrects a use of one style and adjusts some font spacing.
`DetailButton`s are now at 0.07 letter spacing by default.
> Exhibition Details Screen style fixes (AIC-409)

- audio/src/main/res/layout/view_number_pad_numeric_element.xml
- base/src/main/res/drawable/ic_pause.xml
- media_ui/src/main/res/layout/fragment_bottom_audio_player.xml
- media_ui/src/main/res/values/colors.xml
- media_ui/src/main/res/values/dimens.xml
- search/src/main/res/layout/activity_search.xml
Updates
* dialer numbers are displayed in tabular format
* updates the size of the narrow audio player
* update pause button (imports correct SVG from Zepplin)
> Updates design of Narrow audio player (AIC-417)

- base/src/main/res/values/dimens.xml
- base/src/main/res/values/styles.xml
- media_ui/src/main/java/edu/artic/language/LanguageAdapter.kt
- media_ui/src/main/java/edu/artic/language/LanguageSelectorViewBackground.kt
- media_ui/src/main/res/drawable/exo_scrubber.xml
- media_ui/src/main/res/layout/exo_playback_control_view.xml
- media_ui/src/main/res/layout/fragment_audio_details.xml
- media_ui/src/main/res/layout/language_cell.xml
- media_ui/src/main/res/layout/view_language_box.xml
Changes:
* Updates the player control icon size and margin. 
* Updates the language selector view
> Fixes Design of Audio Details Screen : (AIC-420)

- events/src/main/res/layout/cell_all_events_layout.xml
Mostly updates margin and spacing between the components inside the `cell_all_events_layout`
> Copy cell style from `all_tours` to `all events` (AIC-413)

- tours/src/main/kotlin/edu/artic/tours/AllToursViewModel.kt
This covers an oversight from a previous translation task (#220)
> Translate tour properties for the All Tours screen as needed (AIC-561)

- map/src/main/res/layout/layout_amenity_search_cell.xml
- map/src/main/res/layout/layout_artwork_search_cell.xml
- map/src/main/res/layout/layout_exhibition_search_cell.xml
- search/src/main/res/values-en/strings.xml
- search/src/main/res/values-es/strings.xml
- search/src/main/res/values-zh/strings.xml
- search/src/main/res/values/strings.xml
This covers some translation, and a few minor tweaks to the tools-time appearance of the search results card.
> Translate exhibition card title (AIC-578)

- splash/src/main/res/values/styles.xml
This way it won't try to inherit from the wrong source.
> Increase contrast of Splash Screen's ProgressBar

- access_card/src/main/java/edu/artic/accesscard/AccessMemberCardFragment.kt
- access_card/src/main/java/edu/artic/accesscard/AccessMemberCardViewModel.kt
- access_card/src/main/res/layout/fragment_validate_member_information.xml
- app/build.gradle
- audio/src/main/res/layout/fragment_audio_lookup.xml
- events/src/main/res/layout/fragment_all_events.xml
- exhibitions/src/main/kotlin/edu/artic/exhibitions/AllExhibitionsFragment.kt
- exhibitions/src/main/kotlin/edu/artic/exhibitions/AllExhibitionsViewModel.kt
- exhibitions/src/main/res/layout/fragment_all_exhibitions.xml
- info/src/main/res/layout/fragment_museum_information.xml
- localization_ui/src/main/res/layout/fragment_language_settings.xml
- location_ui/src/main/res/layout/fragment_location_settings.xml
- map/src/main/kotlin/edu/artic/map/SearchedObjectsAdapter.kt
- map/src/main/res/layout/fragment_map.xml
- splash/src/main/res/values/styles.xml
- tours/src/main/res/layout/fragment_all_tours.xml
- ui/src/main/res/layout/view_app_bar_layout.xml
- ui/src/main/res/values/styles.xml
This includes all the work made on the `dev` branch since commit 9b11d86. Of special note is commit 1e00d06, which bumps the version name up to 1.0.0.
> Prepping for release of 1.0 to store

- location_ui/src/main/res/layout/fragment_location_prompt.xml
- map/src/main/res/layout/view_marker_department.xml
Fixes design issues mentioned in AIC-506 & AIC-507 tickets.
> Map design update

- map/src/main/kotlin/edu/artic/map/MapObjectDetailsFragment.kt
- map/src/main/kotlin/edu/artic/map/MapObjectDetailsViewModel.kt
Fixes AIC-583, `gallery` text is translated now.
> Localizes gallery in map object details

- build.gradle
- db/src/main/kotlin/edu/artic/db/AppDataManager.kt
- db/src/main/kotlin/edu/artic/db/daos/ArticAudioFileDao.kt
- db/src/main/kotlin/edu/artic/db/daos/ArticGalleryDao.kt
- db/src/main/kotlin/edu/artic/db/daos/ArticObjectDao.kt
- image/build.gradle
- image/src/main/java/edu/artic/image/GlideModule.kt
- map/src/main/kotlin/edu/artic/map/rendering/GlideMapTileProvider.kt
* Fixes the tile image cache issue (AIC-610)
* Removes the artic objects before updating so that removed objects in server are also removed by app (AIC-611)
> Fixes map tile image cache issue

- app/build.gradle
Not much here, really. Version name to 1.0.2, version code to 1002.
> Bump versions for 1.0.2 (AIC-615)

- app/src/main/kotlin/edu/artic/ArticApp.kt
- splash/src/main/kotlin/edu/artic/splash/SplashActivity.kt
This captures some RX errors that could otherwise be a bit harder to analyse.
> Log more errors in debug builds

- content_listing/src/main/kotlin/edu/artic/exhibitions/AllExhibitionsAdapter.kt
- content_listing/src/main/kotlin/edu/artic/exhibitions/AllExhibitionsViewModel.kt
- db/src/main/kotlin/edu/artic/db/AppDataManager.kt
- db/src/main/kotlin/edu/artic/db/AppDatabase.kt
- db/src/main/kotlin/edu/artic/db/models/ArticExhibition.kt
- details/src/main/kotlin/edu/artic/exhibitions/ExhibitionDetailFragment.kt
- details/src/main/kotlin/edu/artic/exhibitions/ExhibitionDetailViewModel.kt
- map/src/main/kotlin/edu/artic/map/SearchObjectDetailsViewModel.kt
- map/src/main/kotlin/edu/artic/map/SearchedObjectsAdapter.kt
- map/src/main/kotlin/edu/artic/map/rendering/MapItemModel.kt
- search/src/main/java/edu/artic/search/SearchResultCellViewModels.kt
- search/src/main/java/edu/artic/search/SearchResultsAdapter.kt
- welcome/src/main/kotlin/edu/artic/welcome/WelcomeExhibitionAdapter.kt
- welcome/src/main/kotlin/edu/artic/welcome/WelcomeViewModel.kt
* Adds the new attribute `image_url` to `ArticExhibition`
* Updates the view logic so that imageView's size is used to build the image URL 
`url=baseurl?w=imageView.measuredWidth&h=imageView.measuredHeight`
> Use new property for exhibition images (AIC-612)

- map/src/main/kotlin/edu/artic/map/MapViewModel.kt
- map/src/main/kotlin/edu/artic/map/rendering/MapItemRenderer.kt
* Focuses tour intro pin properly when the map is launched in tour mode (AIC-613).
* Updates tour stop in carousel and map when the user selects new tour stop from tour details page without changing tour.
> Focuses tour intro pin properly when the map is launched in tour mode - (AIC-613)

- app/build.gradle
This just increases the version code to 1100 and changes its name to 1.1.0.
> Bump versions for 1.1.0 (AIC-632)

- db/schemas/edu.artic.db.AppDatabase/11.json
- db/src/main/kotlin/edu/artic/db/AppDatabase.kt
- db/src/main/kotlin/edu/artic/db/models/ArticGallery.kt
- db/src/main/kotlin/edu/artic/db/models/ArticGeneralInfo.kt
- db/src/main/kotlin/edu/artic/db/models/ArticObject.kt
Removes unused non-optional fields from the model classes.
> Remove unused mandatory fields : AIC-648
